### ISSUE TITLE
一些反馈

### ISSUE THREAD

**Issue by TheMoonOfTides** [ZhengHongrui/QPaiCNS#2]
负魔有点恶心，概率调低一点吧

**Comment by TheMoonOfTides** [comment]
血月怪物添加更多稀有物品吧，概率嘛0.x~个位数？
血月刷怪的种类能改吧？能的话，加一些强力怪吧，卫道士这种强力怪，也可以刷蛮兵这类小boss，与之相对的，会掉落更多物品，并且稀有物品掉率上升

**Comment by ZhengHongrui** [comment]
感谢您的反馈：
负魔相关指数会调低几个百分点，血月暂时不添加更多稀有物品，目前所有物品足够发展
