### ISSUE TITLE
服务器问题

### ISSUE THREAD

**Issue by 2085666593** [ZhengHongrui/QPaiCNS#3]
（希望尽快可以用区块加载器）
领地有俩权限不能给别
蓬松的机器有bug
没有粘液科技的附属插件:无尽科技（希望快点修复之前的那个bug）

**Comment by ZhengHongrui** [comment]
感谢您的反馈：
请问是哪两个权限无法给予他人呢。
蓬松机器bug将会在本周之内发布修复方案。
无尽科技正在测试最新插件结果将会在两周内公布。

**Comment by 2085666593** [comment]
> 感谢您的反馈： 请问是哪两个权限无法给予他人呢。蓬松机器bug将会在本周之内发布修复方案。无尽科技正在测试最新插件结果将会在两周内公布。

领地的shear权限和leash权限不能给

**Comment by ZhengHongrui** [comment]
已经修复
