### ISSUE TITLE
来自hanpor的反馈

### ISSUE THREAD

**Issue by TheMoonOfTides** [ZhengHongrui/QPaiCNS#5]
添加粘液科技材质包
自动清理插件会清理矿车,并且会吞并矿车上的生物

**Comment by ZhengHongrui** [comment]
感谢您的反馈：
粘液科技材质包将会在本周内添加入整合包制作计划。
自动插件清理矿车漏洞将会在两个工作日内修复。
生物防止清除请使用命名牌命名以达到防止清除的作用。
